import { Task, TaskPriority, TaskStatus, TaskType } from "../../../../types/tasks";

export const TASKS: Task[] = [
  {
    id: 'TASK-8438',
    title: 'Implement webhooks for real-time notifications',
    type: TaskType.Feature,
    status: TaskStatus.Done,
    priority: TaskPriority.High,
  },
  {
    id: 'TASK-9800',
    title: 'Add support for custom user avatars',
    type: TaskType.Feature,
    status: TaskStatus.Done,
    priority: TaskPriority.Low,
  },
  {
    id: 'TASK-3650',
    title: 'Add support for user-generated content moderation',
    type: TaskType.Feature,
    status: TaskStatus.Canceled,
    priority: TaskPriority.Medium,
  },
  {
    id: 'TASK-2743',
    title: 'Implement password reset functionality for users',
    type: TaskType.Documentation,
    status: TaskStatus.Todo,
    priority: TaskPriority.High,
  },
  {
    id: 'TASK-3168',
    title: 'Implement webhooks for real-time notifications',
    type: TaskType.Documentation,
    status: TaskStatus.InProgress,
    priority: TaskPriority.Medium,
  },
  {
    id: 'TASK-9948',
    title: 'Add support for custom user avatars',
    type: TaskType.Bug,
    status: TaskStatus.Done,
    priority: TaskPriority.High,
  },
  {
    id: 'TASK-7538',
    title: 'Implement content moderation system for user-generated content',
    type: TaskType.Bug,
    status: TaskStatus.Done,
    priority: TaskPriority.High,
  },
  {
    id: 'TASK-8047',
    title: 'Update error messages for clarity and user-friendliness',
    type: TaskType.Feature,
    status: TaskStatus.Backlog,
    priority: TaskPriority.High,
  },
  {
    id: 'TASK-2962',
    title: 'Add support for file uploads in the application',
    type: TaskType.Feature,
    status: TaskStatus.InProgress,
    priority: TaskPriority.High,
  },
  {
    id: 'TASK-2395',
    title: 'Implement user search functionality with filters',
    type: TaskType.Documentation,
    status: TaskStatus.Canceled,
    priority: TaskPriority.Low,
  },
  {
    id: 'TASK-8545',
    title: 'Implement data validation for user inputs',
    type: TaskType.Feature,
    status: TaskStatus.Done,
    priority: TaskPriority.Medium,
  },
  {
    id: 'TASK-8798',
    title: 'Implement lazy loading for images and videos',
    type: TaskType.Documentation,
    status: TaskStatus.Backlog,
    priority: TaskPriority.Low,
  },
  {
    id: 'TASK-6139',
    title: 'Integrate single sign-on (SSO) authentication',
    type: TaskType.Feature,
    status: TaskStatus.Done,
    priority: TaskPriority.Medium,
  },
  {
    id: 'TASK-3580',
    title: 'Update frontend frameworks to the latest versions',
    type: TaskType.Bug,
    status: TaskStatus.Todo,
    priority: TaskPriority.Low,
  },
  {
    id: 'TASK-2552',
    title: 'Add support for user tagging in content',
    type: TaskType.Documentation,
    status: TaskStatus.InProgress,
    priority: TaskPriority.High,
  },
  {
    id: 'TASK-7935',
    title: 'Optimize database indexes for improved query performance',
    type: TaskType.Documentation,
    status: TaskStatus.Backlog,
    priority: TaskPriority.Low,
  },
  {
    id: 'TASK-4658',
    title: 'Implement two-factor authentication for user accounts',
    type: TaskType.Feature,
    status: TaskStatus.Done,
    priority: TaskPriority.Low,
  },
  {
    id: 'TASK-6193',
    title: 'Add support for rich text editing in user comments',
    type: TaskType.Feature,
    status: TaskStatus.Backlog,
    priority: TaskPriority.Medium,
  },
  {
    id: 'TASK-8391',
    title: 'Optimize database schema for scalability',
    type: TaskType.Feature,
    status: TaskStatus.Canceled,
    priority: TaskPriority.High,
  },
  {
    id: 'TASK-5770',
    title: 'Update cookie management for GDPR compliance',
    type: TaskType.Documentation,
    status: TaskStatus.Done,
    priority: TaskPriority.Low,
  },
  {
    id: 'TASK-6194',
    title: 'Implement scheduled tasks for automated maintenance',
    type: TaskType.Feature,
    status: TaskStatus.Todo,
    priority: TaskPriority.Medium,
  },
  {
    id: 'TASK-8706',
    title: 'Update SSL certificates for secure connections',
    type: TaskType.Documentation,
    status: TaskStatus.Todo,
    priority: TaskPriority.Medium,
  },
  {
    id: 'TASK-5409',
    title: 'Add support for rich text editing in user comments',
    type: TaskType.Bug,
    status: TaskStatus.Backlog,
    priority: TaskPriority.Medium,
  },
  {
    id: 'TASK-5935',
    title: 'Create automated backups for data recovery',
    type: TaskType.Feature,
    status: TaskStatus.Todo,
    priority: TaskPriority.Low,
  },
  {
    id: 'TASK-3311',
    title: 'Update error logging and monitoring system',
    type: TaskType.Documentation,
    status: TaskStatus.Done,
    priority: TaskPriority.Medium,
  },
  {
    id: 'TASK-5596',
    title: 'Implement two-factor authentication for user accounts',
    type: TaskType.Feature,
    status: TaskStatus.Canceled,
    priority: TaskPriority.Low,
  },
  {
    id: 'TASK-8352',
    title: 'Update caching strategy for improved performance',
    type: TaskType.Feature,
    status: TaskStatus.Done,
    priority: TaskPriority.Low,
  },
  {
    id: 'TASK-8619',
    title: 'Create user dashboard with personalized recommendations',
    type: TaskType.Bug,
    status: TaskStatus.Canceled,
    priority: TaskPriority.High,
  },
  {
    id: 'TASK-2215',
    title: 'Implement password reset functionality for users',
    type: TaskType.Feature,
    status: TaskStatus.Todo,
    priority: TaskPriority.Low,
  },
  {
    id: 'TASK-1913',
    title: 'Implement content filtering for inappropriate content',
    type: TaskType.Feature,
    status: TaskStatus.Done,
    priority: TaskPriority.Low,
  },
  {
    id: 'TASK-3601',
    title: 'Update cookie management for GDPR compliance',
    type: TaskType.Documentation,
    status: TaskStatus.Backlog,
    priority: TaskPriority.High,
  },
  {
    id: 'TASK-2644',
    title: 'Update user dashboard with performance metrics',
    type: TaskType.Documentation,
    status: TaskStatus.InProgress,
    priority: TaskPriority.Medium,
  },
  {
    id: 'TASK-4478',
    title: 'Optimize database queries using query caching',
    type: TaskType.Bug,
    status: TaskStatus.Canceled,
    priority: TaskPriority.Medium,
  },
  {
    id: 'TASK-2123',
    title: 'Update branding and logo across the application',
    type: TaskType.Feature,
    status: TaskStatus.Canceled,
    priority: TaskPriority.Medium,
  },
  {
    id: 'TASK-2174',
    title: 'Optimize client-side performance with code splitting',
    type: TaskType.Feature,
    status: TaskStatus.Canceled,
    priority: TaskPriority.High,
  },
  {
    id: 'TASK-3258',
    title: 'Implement data validation for user inputs',
    type: TaskType.Feature,
    status: TaskStatus.Backlog,
    priority: TaskPriority.Medium,
  },
  {
    id: 'TASK-4392',
    title: 'Implement browser caching for static assets',
    type: TaskType.Documentation,
    status: TaskStatus.Done,
    priority: TaskPriority.Medium,
  },
  {
    id: 'TASK-3658',
    title: 'Update frontend frameworks to the latest versions',
    type: TaskType.Bug,
    status: TaskStatus.Backlog,
    priority: TaskPriority.Low,
  },
  {
    id: 'TASK-7717',
    title: 'Update SSL certificates for secure connections',
    type: TaskType.Feature,
    status: TaskStatus.InProgress,
    priority: TaskPriority.High,
  },
  {
    id: 'TASK-6641',
    title: 'Update error messages for clarity and user-friendliness',
    type: TaskType.Documentation,
    status: TaskStatus.InProgress,
    priority: TaskPriority.High,
  },
  {
    id: 'TASK-6752',
    title: 'Implement pagination for long lists of data',
    type: TaskType.Documentation,
    status: TaskStatus.Canceled,
    priority: TaskPriority.Medium,
  },
  {
    id: 'TASK-7921',
    title: 'Implement content moderation system for user-generated content',
    type: TaskType.Bug,
    status: TaskStatus.Todo,
    priority: TaskPriority.Low,
  },
  {
    id: 'TASK-6192',
    title: 'Add support for user tagging in content',
    type: TaskType.Documentation,
    status: TaskStatus.InProgress,
    priority: TaskPriority.Low,
  },
  {
    id: 'TASK-6066',
    title: 'Create admin dashboard for managing user accounts',
    type: TaskType.Documentation,
    status: TaskStatus.Todo,
    priority: TaskPriority.Low,
  },
  {
    id: 'TASK-3607',
    title: 'Implement password strength meter for user registration',
    type: TaskType.Documentation,
    status: TaskStatus.InProgress,
    priority: TaskPriority.Low,
  },
  {
    id: 'TASK-7596',
    title: 'Add support for user authentication via social media',
    type: TaskType.Bug,
    status: TaskStatus.Done,
    priority: TaskPriority.Medium,
  },
  {
    id: 'TASK-8060',
    title: 'Optimize image compression settings for faster loading',
    type: TaskType.Bug,
    status: TaskStatus.Todo,
    priority: TaskPriority.Low,
  },
  {
    id: 'TASK-4360',
    title: 'Add support for user bookmarks and favorites',
    type: TaskType.Feature,
    status: TaskStatus.Canceled,
    priority: TaskPriority.Medium,
  },
  {
    id: 'TASK-9674',
    title: 'Add support for user bookmarks and favorites',
    type: TaskType.Bug,
    status: TaskStatus.InProgress,
    priority: TaskPriority.Low,
  },
  {
    id: 'TASK-9457',
    title: 'Optimize database connections for connection pooling',
    type: TaskType.Feature,
    status: TaskStatus.Canceled,
    priority: TaskPriority.Low,
  },
  {
    id: 'TASK-8805',
    title: 'Integrate single sign-on (SSO) authentication',
    type: TaskType.Feature,
    status: TaskStatus.Done,
    priority: TaskPriority.High,
  },
  {
    id: 'TASK-8860',
    title: 'Create automated backups for data recovery',
    type: TaskType.Feature,
    status: TaskStatus.Todo,
    priority: TaskPriority.Medium,
  },
  {
    id: 'TASK-6522',
    title: 'Update cookie management for GDPR compliance',
    type: TaskType.Documentation,
    status: TaskStatus.Canceled,
    priority: TaskPriority.Medium,
  },
  {
    id: 'TASK-1634',
    title: 'Update notification preferences for user settings',
    type: TaskType.Documentation,
    status: TaskStatus.Todo,
    priority: TaskPriority.High,
  },
  {
    id: 'TASK-4754',
    title: 'Add user notifications for important events',
    type: TaskType.Bug,
    status: TaskStatus.Canceled,
    priority: TaskPriority.Low,
  },
  {
    id: 'TASK-2645',
    title: 'Implement lazy loading for images and videos',
    type: TaskType.Bug,
    status: TaskStatus.Todo,
    priority: TaskPriority.Medium,
  },
  {
    id: 'TASK-1052',
    title: 'Design and implement a dark mode theme for the app',
    type: TaskType.Bug,
    status: TaskStatus.Canceled,
    priority: TaskPriority.Low,
  },
  {
    id: 'TASK-5892',
    title: 'Implement user search functionality with filters',
    type: TaskType.Documentation,
    status: TaskStatus.InProgress,
    priority: TaskPriority.Medium,
  },
  {
    id: 'TASK-2111',
    title: 'Update UI animations for smoother transitions',
    type: TaskType.Documentation,
    status: TaskStatus.Canceled,
    priority: TaskPriority.Low,
  },
  {
    id: 'TASK-2178',
    title: 'Add progress indicators for long-running tasks',
    type: TaskType.Documentation,
    status: TaskStatus.Todo,
    priority: TaskPriority.High,
  },
  {
    id: 'TASK-9597',
    title: 'Update branding and logo across the application',
    type: TaskType.Feature,
    status: TaskStatus.Done,
    priority: TaskPriority.Low,
  },
  {
    id: 'TASK-1089',
    title: 'Implement lazy loading for images and videos',
    type: TaskType.Bug,
    status: TaskStatus.InProgress,
    priority: TaskPriority.Medium,
  },
  {
    id: 'TASK-8140',
    title: 'Implement user feedback rating system',
    type: TaskType.Feature,
    status: TaskStatus.Backlog,
    priority: TaskPriority.Low,
  },
  {
    id: 'TASK-5384',
    title: 'Update user interface with responsive design patterns',
    type: TaskType.Bug,
    status: TaskStatus.Done,
    priority: TaskPriority.Medium,
  },
  {
    id: 'TASK-6203',
    title: 'Add error handling to form submissions',
    type: TaskType.Bug,
    status: TaskStatus.Backlog,
    priority: TaskPriority.Medium,
  },
  {
    id: 'TASK-3263',
    title: 'Update user dashboard with performance metrics',
    type: TaskType.Bug,
    status: TaskStatus.InProgress,
    priority: TaskPriority.Medium,
  },
  {
    id: 'TASK-6908',
    title: 'Implement user activity logging for auditing',
    type: TaskType.Documentation,
    status: TaskStatus.Todo,
    priority: TaskPriority.High,
  },
  {
    id: 'TASK-3704',
    title: 'Optimize database connections for connection pooling',
    type: TaskType.Feature,
    status: TaskStatus.Todo,
    priority: TaskPriority.High,
  },
  {
    id: 'TASK-9868',
    title: 'Implement password reset functionality for users',
    type: TaskType.Feature,
    status: TaskStatus.Backlog,
    priority: TaskPriority.High,
  },
  {
    id: 'TASK-6317',
    title: 'Optimize database schema for scalability',
    type: TaskType.Feature,
    status: TaskStatus.InProgress,
    priority: TaskPriority.Medium,
  },
  {
    id: 'TASK-2711',
    title: 'Optimize SQL queries for faster database performance',
    type: TaskType.Bug,
    status: TaskStatus.InProgress,
    priority: TaskPriority.Low,
  },
  {
    id: 'TASK-7827',
    title: 'Add error handling to form submissions',
    type: TaskType.Feature,
    status: TaskStatus.InProgress,
    priority: TaskPriority.Medium,
  },
  {
    id: 'TASK-5029',
    title: 'Create interactive data visualizations for analytics',
    type: TaskType.Feature,
    status: TaskStatus.Canceled,
    priority: TaskPriority.Medium,
  },
  {
    id: 'TASK-1881',
    title: 'Update user interface with responsive design patterns',
    type: TaskType.Feature,
    status: TaskStatus.Backlog,
    priority: TaskPriority.Medium,
  },
  {
    id: 'TASK-3308',
    title: 'Add user notifications for important events',
    type: TaskType.Documentation,
    status: TaskStatus.InProgress,
    priority: TaskPriority.High,
  },
  {
    id: 'TASK-3332',
    title: 'Update privacy policy and terms of service pages',
    type: TaskType.Bug,
    status: TaskStatus.Done,
    priority: TaskPriority.High,
  },
  {
    id: 'TASK-2579',
    title: 'Optimize client-side performance with code splitting',
    type: TaskType.Bug,
    status: TaskStatus.Canceled,
    priority: TaskPriority.High,
  },
  {
    id: 'TASK-5412',
    title: 'Integrate single sign-on (SSO) authentication',
    type: TaskType.Bug,
    status: TaskStatus.InProgress,
    priority: TaskPriority.High,
  },
  {
    id: 'TASK-6975',
    title: 'Create automated tests for critical user flows',
    type: TaskType.Documentation,
    status: TaskStatus.Canceled,
    priority: TaskPriority.Medium,
  },
  {
    id: 'TASK-7466',
    title: 'Implement data export functionality for users',
    type: TaskType.Bug,
    status: TaskStatus.Todo,
    priority: TaskPriority.High,
  },
  {
    id: 'TASK-5866',
    title: 'Create admin dashboard for managing user accounts',
    type: TaskType.Documentation,
    status: TaskStatus.Canceled,
    priority: TaskPriority.High,
  },
  {
    id: 'TASK-7056',
    title: 'Add support for user-defined data fields',
    type: TaskType.Feature,
    status: TaskStatus.Done,
    priority: TaskPriority.Low,
  },
  {
    id: 'TASK-1308',
    title: 'Update cookie management for GDPR compliance',
    type: TaskType.Bug,
    status: TaskStatus.Todo,
    priority: TaskPriority.Low,
  },
  {
    id: 'TASK-7161',
    title: 'Add support for user bookmarks and favorites',
    type: TaskType.Documentation,
    status: TaskStatus.Canceled,
    priority: TaskPriority.High,
  },
  {
    id: 'TASK-2868',
    title: 'Implement password reset functionality for users',
    type: TaskType.Feature,
    status: TaskStatus.Todo,
    priority: TaskPriority.Low,
  },
  {
    id: 'TASK-4764',
    title: 'Add keyboard shortcuts for common actions',
    type: TaskType.Bug,
    status: TaskStatus.Canceled,
    priority: TaskPriority.High,
  },
  {
    id: 'TASK-1412',
    title: 'Implement password reset functionality for users',
    type: TaskType.Documentation,
    status: TaskStatus.InProgress,
    priority: TaskPriority.Low,
  },
  {
    id: 'TASK-1707',
    title: 'Update cookie management for GDPR compliance',
    type: TaskType.Bug,
    status: TaskStatus.Done,
    priority: TaskPriority.Low,
  },
  {
    id: 'TASK-8871',
    title: 'Implement password reset functionality for users',
    type: TaskType.Bug,
    status: TaskStatus.Done,
    priority: TaskPriority.Low,
  },
  {
    id: 'TASK-2924',
    title: 'Integrate chat support widget into the application',
    type: TaskType.Documentation,
    status: TaskStatus.Canceled,
    priority: TaskPriority.Medium,
  },
  {
    id: 'TASK-7170',
    title: 'Implement API rate limiting for third-party integrations',
    type: TaskType.Feature,
    status: TaskStatus.Todo,
    priority: TaskPriority.Medium,
  },
  {
    id: 'TASK-5354',
    title: 'Optimize client-side performance with code splitting',
    type: TaskType.Bug,
    status: TaskStatus.Todo,
    priority: TaskPriority.High,
  },
  {
    id: 'TASK-6459',
    title: 'Add user notifications for important events',
    type: TaskType.Documentation,
    status: TaskStatus.Backlog,
    priority: TaskPriority.Low,
  },
  {
    id: 'TASK-2449',
    title: 'Create user onboarding tutorial for new sign-ups',
    type: TaskType.Bug,
    status: TaskStatus.Canceled,
    priority: TaskPriority.Medium,
  },
  {
    id: 'TASK-9645',
    title: 'Implement user feedback mechanism for feature requests',
    type: TaskType.Bug,
    status: TaskStatus.Canceled,
    priority: TaskPriority.High,
  },
  {
    id: 'TASK-3511',
    title: 'Add user notifications for important events',
    type: TaskType.Feature,
    status: TaskStatus.InProgress,
    priority: TaskPriority.Low,
  },
  {
    id: 'TASK-6853',
    title: 'Create interactive data visualizations for analytics',
    type: TaskType.Feature,
    status: TaskStatus.Done,
    priority: TaskPriority.Low,
  },
  {
    id: 'TASK-3432',
    title: 'Update API documentation with examples and usage',
    type: TaskType.Bug,
    status: TaskStatus.Canceled,
    priority: TaskPriority.Medium,
  },
  {
    id: 'TASK-7328',
    title: 'Fix memory leaks in background processing tasks',
    type: TaskType.Documentation,
    status: TaskStatus.Done,
    priority: TaskPriority.High,
  },
  {
    id: 'TASK-8727',
    title: 'Update frontend frameworks to the latest versions',
    type: TaskType.Documentation,
    status: TaskStatus.Todo,
    priority: TaskPriority.High,
  },
]
